wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1676955189.488417
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.8
      5: 0.13.9
      8:
      - 5
algo:
  desc: null
  value: maddpg
batch_size:
  desc: null
  value: 32
buffer_limit:
  desc: null
  value: 50000
env_name:
  desc: null
  value: ma_gym:PredatorPrey5x5-v1
gamma:
  desc: null
  value: 0.99
gumbel_max_temp:
  desc: null
  value: 10
gumbel_min_temp:
  desc: null
  value: 0.1
log_interval:
  desc: null
  value: 20
lr_mu:
  desc: null
  value: 0.0005
lr_q:
  desc: null
  value: 0.001
max_episodes:
  desc: null
  value: 10
tau:
  desc: null
  value: 0.005
test_episodes:
  desc: null
  value: 5
update_iter:
  desc: null
  value: 10
warm_up_steps:
  desc: null
  value: 2000
